# code deploy 가 어떻게 행동할지 정의 하는 파일

version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/deploy/ssm_node/ # S3에서 가지고온 파일을 저장할 디렉터리 지정
    overwrite: yes
hooks:
  AfterInstall: # 배포가 끝나면 아래 명령어를 실행
    - location: execute-deploy.sh
      timeout: 180
